config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  #get "firmas/:id", to: "compras#show", as: "compras"
  # patch "/firmas/:id", to: "firmas#vendas", as: "firma_venda"



  resources :firmas, except: [:edit] do
    resources :fornecedores, only: [:index, :show, :edit, :update]
    resources :banks, only: [:index, :show]
    resources :lancamentos, only: [:index, :show, :edit, :update]
    resources :vendas, only: [:update]

  end

end

app/models/firma.rb
class Firma < ApplicationRecord
  belongs_to :user
  has_many :lancamentos
  has_many :banks
  has_many :fornecedores
  has_many :vendas

  has_one_attached :photo, dependent: :destroy

  validates :name, presence: true
  validates :sector, presence: true
  validates :capital, numericality: { greater_than: 0 }
  validates :product, numericality: { greater_than: -1 }
end

app/controllers/firmas_controller.rb
class FirmasController < ApplicationController

  before_action :set_firma, only: [:show, :destroy, :update]
  before_action :set_fornecedor, only: [:update]

  def index
    @firmas = Firma.all.order("capital DESC")
  end


  def new

    @firma = Firma.new
  end

  def create
    @firma = Firma.new(firma_params)
    @firma.user = current_user
    if @firma.save
      redirect_to firma_path(@firma)
    else
      render :new
    end
  end

  def show
  end

  def update
    quantity = firma_params[:product]
    @firma.product += quantity.to_i
    @firma.capital -= quantity.to_i * @fornecedor.preco.to_i
    @firma.compras = @fornecedor.preco.to_i
    value = quantity.to_i * @fornecedor.preco.to_i
    if @firma.save
      Lancamento.create(tipo: "Compra", quantity: quantity.to_i, initcap: @firma.capital + value, saldo: @firma.capital, estoque: @firma.product, value: quantity.to_i * @fornecedor.preco.to_i ,  firma: @firma, date: @firma.periodo)
      # @fornecedor.estoque -= quantity.to_i
      # @fornecedor.save
      redirect_to firma_path(@firma)
    else
      redirect_to firma_path(@firma), notice: "Você não tem dinheiro para isso! Quer fazer um empréstimo?"
    end
  end

  # tentativa de fazer um metodo (rota não leva para o id da firma)

  # def venda
  #   @firma = Firma.find(params[:firma_id])
  #   valor_vendas = @firma.compras + 20
  #   quantidade_vendas = rand(10..@firma.product)
  #   @firma.product -= quantidade_vendas
  #   @firma.capital += quantidade_vendas * valor_vendas
  #   value = quantidade_vendas * valor_vendas
  #   raise
  #   if @firma.save
  #     Lancamento.create(tipo: "Venda", quantity: quantidade_vendas.to_i, initcap: @firma.capital - value, saldo: @firma.capital, estoque: @firma.product, value: value ,  firma: @firma, date: Time.now)
  #     redirect_to firma_lancamento_path(@firma)
  #   else
  #     redirect_to firma_path(@firma), notice: "Bug no sistema"
  #   end
  # end

  def destroy
    @firma.destroy
    redirect_to firmas_path(current_user)
  end

  private

  def set_fornecedor
    @fornecedor = Fornecedor.find(params[:fornecedor_id])
  end

  def firma_params
    params.require(:firma).permit(:name, :sector, :capital, :product, :photo, :sales, :periodo, :user_id)
  end


  def set_firma
    @firma = Firma.find(params[:id])  
  end
end

app/helpers/firmas_helper.rb
module FirmasHelper
end

app/views/firmas/_form.html.erb
<div class='container bg-trasparent my-2 p-1'>
  <div class="card">
  <div class="card-header text-center">
    <% @user = User.find(current_user.id)  %>
    <h2>Cadastramento de Firmas <br>para <%= @user.first_name %> <%= @user.last_name %></h2>
  </div>
  <br>
  <div class="card-body">
  <%= simple_form_for(@firma) do |f| %>
    <%= f.input :name, required: true, placeholder: 'O nome da empresa' %>
    <%= f.input :sector, as: :radio_buttons, collection: [['Vestuário', 'Vestuário'], ['Alimentação', 'Alimentação'], ['Brinquedo', 'Brinquedo']], label_method: :second, value_method: :first, :item_wrapper_class => 'radio_buttons', :default => true %>
      <br>
     <%= f.input :photo, as: :file %>
     <br>
    <%= content_tag(:div, class: 'form-group') do %>
      <%= content_tag(:div, class: 'col-sm-offset-2') do %>
        <%= f.button :submit, class: "btn btn-success rounded-pill" %>
      <% end %>
    <% end %>
  <% end %>
</div>
</div>
</div>

app/views/firmas/index.html.erb
<div class='container bg-trasparent my-2 p-1'>
<nav class="navbar navbar-light bg-light d-flex justify-content-between">
<h1>Rank das firmas</h1>
<%= image_tag ("https://source.unsplash.com/qfp4-Ud6Fyg"), class: "avatar-square" %>
</nav>
<br>

<table class="table table-light table-striped table-hover">
<thead class="table-light table-sm align-middle text-center">
  <tr>
    <td> Avatar </td>
    <td> User</td>
    <td> Firma </td>
    <td> Setor</td>
    <td> Estoque </td>
    <td> Qtd Vendida</td>
    <td> Período</td>
    <td> Capital R$ &nbsp;&nbsp;</td>
    
  </tr>
</thead>
<tbody class="align-middle text-center">
<% @firmas.each do |firma| %>
    <tr>
    <% if firma.user.photo.attached? %>
      <th scope="row">  <%= image_tag (firma.user.photo), class: "avatar-small" %> </th>
      <% else %>
       <th scope="row"> <%= image_tag ("logo.png"), class: "avatar-small"%> </th>
      <% end %>
      <th scope="row">  <%= firma.user.first_name%> <%= firma.user.last_name%> </th>
      <th scope="row">  <%= firma.name %> </th>
      <th scope="row">  <%= firma.sector %> </th>
      <th scope="row">  <%= firma.product %> </th>
      <th scope="row">  <%= firma.sales %> </th>
      <th scope="row">  <%= firma.periodo %> </th>
      <th scope="row">  <%= firma.capital %> </th>
    </tr>
 <% end %>
 </tbody>
</table>
  <br>
  <p type="button" class="btn btn-dark rounded-pill"><%= link_to 'Voltar ao Menu!', root_path %></p>
</div>

app/views/firmas/new.html.erb
<%= render 'form' %>

<div class='container bg-trasparent my-2 p-1'>
<%= link_to 'Back to Menu', root_path, class:"btn btn-primary rounded-pill"%>
</div>

app/views/firmas/show.html.erb
<main id="status">
  <div class="container my-4 p-3">
    <div class="card">
      <h1 class="text-center fw-bold"><%= @firma.name %></h1>
      <p class="text-center fst-italic">Área de atuação: <strong><%= @firma.sector %></strong></p>
    </div>


  <div class="container-fluid my-4 p-3">
    <div class="d-flex justify-content-around">
      <div class="badge bg-dark text-wrap" style="width: 130px;">
        <h5><strong>Mês inicial:</strong></h5>
        <h5><%= @firma.created_at.strftime("%m/%y")%></h5>
      </div>
      <div class="badge bg-dark text-wrap" style="width: 130px;">
        <h5><strong>Periodo corrente:</strong></h5>
         <h5><%=@firma.periodo%></h5>
      </div>
      <div class="badge bg-dark text-wrap" style="width: 130px;">
        <h5><strong>Capital:</strong></h5>
        <h5> R$ <%= @firma.capital %></h5>
      </div>
      <div class="badge bg-dark text-wrap" style="width: 130px;">
        <h5><strong>Estoque:</strong>
        <h5><%= @firma.product %> unidades</h5>
      </div>
    </div>
  </div>

  <%# <div class="container-fluid">
    <h5><strong>Previsão para o próximo mês:</strong></h5>
    <p> Digite aqui a previsão!</p>
  </div> %>

  <div class="card" style="height: 90px;">
    <div class= "d-flex mt-4 justify-content-around">
      <p type="button" class="btn btn-success rounded-pill"><%= link_to 'Estoque / Comprar', firma_fornecedores_path(@firma) %></p>
      <p type="button" id="sweet-alert-demo" class="btn btn-success rounded-pill"><%= link_to 'Girar mês / Vender', firma_venda_path(firma_id:@firma.id, notice:"Teste"), method: "PATCH" %></p>
    </div>
  </div>
</div>

app/views/firmas/update.html.erb
<h1> Compra </h1> 