config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  #get "firmas/:id", to: "compras#show", as: "compras"
  # patch "/firmas/:id", to: "firmas#vendas", as: "firma_venda"



  resources :firmas, except: [:edit] do
    resources :fornecedores, only: [:index, :show, :edit, :update]
    resources :banks, only: [:index, :show]
    resources :lancamentos, only: [:index, :show, :edit, :update]
    resources :vendas, only: [:update]

  end

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav id="navbar" class="d-flex">
  <div class="navbar w-100 navbar-expand-sm navbar-light navbar-marketplace" >
    <%= link_to root_path, class: "navbar-brand navbar-collapse collapse" do %>
      <%= image_tag ("logo2.jpeg"), class: "avatar" %>
    <% end %>
  
  
  <!-- Burguer Menu will replace the links when screen width is small enough -->

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <% if current_user.firma == nil %>
          <%= link_to "Firma", new_firma_path, class: "nav-link" %>
          <% else %>
          <%= link_to "Firma", firma_path(current_user.firma), class: "nav-link" %>
          <% end %>
        </li>
            <% if current_user.photo.attached? %>
          <div class="nav-item dropdown "> 
          <a href="#" id="DropdownMenu2" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <%= cl_image_tag current_user.photo.key, class: "avatar"%>
          </a>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="DropdownMenu2">
            <%= link_to "Criar firma", new_firma_path, class: "dropdown-item" %>
            <%= link_to "Restultados", firmas_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </div>
            <% else %>
          <div class="nav-item dropdown"> 
          <a href="#" id="DropdownMenu2" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <%= image_tag ("logo.png"), class: "avatar"%>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="DropdownMenu2">
            <%= link_to "Criar firma", new_firma_path, class: "dropdown-item" %>
            <%= link_to "Restultados", firmas_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </div>
            <% end %>
          
      <% else %>
        <li class="nav-item">
          <%= link_to "Sig in", new_user_registration_path, class: "nav-link" %>
          </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <li class="nav-item">
        <a href="#" id="DropdownMenu2" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <%= image_tag ("logo4.png"), class: "avatar"%>
          </a>
        </li>
      <% end %>
    </ul>
  </div>
  </div>
</nav>